name: Add a random question

on:
  issues:
    types:
      - opened

jobs:
  add-random-question:
    runs-on: ubuntu-latest
    steps:

      - name: debug
        run: |
          echo "comments url:${{ toJson(github.event.issue.comments_url) }}";
          echo "title:${{ toJson(github.event.issue.title) }}";
          echo "${{ github.event.issue.title }}";

