name: Add a random question

on:
  issues:
    types:
      - opened

jobs:
  add-random-question:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'Team Meeting')
    steps:
      - uses: actions/checkout@v2

      - name: Pick random question
        id: random
        run: echo "::set-output name=question::$(shuf -n 1 .github/random-questions.txt)";

      - name: Add a comment
        uses: octokit/request-action@v2.x
        with:
          route: POST ${{ github.event.issue.comments_url }}
          body: ${{ format('Question of the week: {0}', steps.random.outputs.question) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
