name: Add a random question

on:
  issues:
    types:
      - opened

jobs:
  add-random-question:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'Team Meeting')
    steps:

      - name: debug
        run: |
          echo ${{ toJson(github.event.issue.comments_url) }};
          echo ${{ toJson(github.event.issue.title) }};

