name: development

on:
  push:
    branches: [master, v*]
  pull_request:
    branches: ['**']
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'router/**'
      - 'test-client/**'
      - 'utility/**'
      # changes that might affect CI
      - '.github/**'
      - 'e2e/**'
      - 'docker-compose.*.yml'
      - '.env.*'
      - 'Makefile'

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print all
        run: echo "${{ toJson(github.event) }}";
