name: Create a draft release

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Or enter a commit to use (HEAD of the selected branch if empty)'
        required: false
        default: ''

jobs:
  create_draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set commitish
        id: set-commitish
        run: |-
          if [[ -z "${{ github.event.inputs.commit }}" ]]; then
            # no commit is entered
            echo "::set-output name=commitish::$GITHUB_SHA";
          else
            echo "::set-output name=commitish::${{ github.event.inputs.commit }}";
          fi

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ steps.set-commitish.outputs.commitish }}

      - name: Determinate latest released tag
        id: latest-tag
        run: |-
          tag=$( git tag -l --merged master "v*.*.*" --sort=-committerdate | head -n 1 );
          echo "::set-output name=tag::$tag";

      - name: Parse version
        id: parse-version
        run: |-
          [[ "${{ steps.latest-tag.outputs.tag }}" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-[A-Z0-9]+){0,1}$ ]]
          MAJOR="${BASH_REMATCH[1]}"
          MINOR="${BASH_REMATCH[2]}"
          PATCH="${BASH_REMATCH[3]}"
          echo "$MAJOR - $MINOR - $PATCH"
#
#      - uses: release-drafter/release-drafter@v5
#        with:
#          config-name: release-drafter-onprem.yml
#          commitish: ${{ steps.set-commitish.outputs.commitish }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
