name: Notify on label
on:
  issues:
    types: [labeled]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event.issue.labels) }}"
      - run: echo "${{ toJSON(github.event.label) }}"
