name: Notify on label
on:
  issues:
    types: [labeled]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.issue.labels }}"
      - run: echo "${{ github.event.label }}"
