name: Notify on label
on:
  issues:
    types: [labeled]
jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issues.*.name, 'bug') && startsWith(github.event.label.name, 'test') }}
    steps:
      - name: Add a comment
        uses: octokit/request-action@v2.x
        with:
          route: POST ${{ github.event.issue.comments_url }}
          body: "${{ format('@{0} the issue was fixed and released in {1}', github.event.issue.user.login, github.event.label.name) }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
