name: test prerelease

on:
  release:
    types: [ published ]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print all
        run: echo "${{ toJson(github.event) }}";
  echo-prerelease:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == true
    steps:
      - run: echo "prereleased"
  echo-release:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false
    steps:
      - run: echo "release"
