name: test release format v*.*.*

on:
  release:
    types: [ released ]

jobs:
  release-format:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check-release-format.outputs.result }}
    steps:
      - name: Determinate if release matches onprem format
        id: check-release-format
        run: |-
          if [[ "${{ github.event.release.tag_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[A-Z0-9]+){0,1}$ ]]; then
            echo "::set-output name=result::true";
          else
            echo "::set-output name=result::false";
          fi
  print:
    runs-on: ubuntu-latest
    needs: release-format
    steps:
      - name: print
        run: echo "${{ needs.release-format.outputs.result }}";
      - name: print all
        run: echo "${{ toJson(needs) }}";
  publish:
    runs-on: ubuntu-latest
    needs: release-format
    if: ${{ needs.release-format.outputs.result == 'true' }}
    steps:
      - name: Do something
        run: echo "releasing"
