name: test release format v*.*.*

on:
  release:
    types: [ released ]

jobs:
  release-format:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.should-release.outputs.result }}
    steps:
      - name: Set release
        run: echo "IAM_RELEASE=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Determinate if release matches onprem format
        run: |-
          if [[ $IAM_RELEASE =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::set-output name=result::true";
          fi
  print:
    runs-on: ubuntu-latest
    needs: release-format
    steps:
      - name: print
        run: echo "${{ needs.release-format.outputs.result }}";
      - name: print all
        run: echo "${{ toJson(needs) }}";
  publish:
    runs-on: ubuntu-latest
    needs: release-format
    if: ${{ needs.release-format.outputs.result }} == 'true'
    steps:
      - name: Do something
        run: echo "${IAM_RELEASE}"
