name: test release format v*

on:
  release:
    types: [ released ]

jobs:
  release-format:
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{ steps.should-release.outputs.result }}
    steps:
      - name: Set release
        run: echo "IAM_RELEASE=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Determinate if release matches SaaS format
        run: |-
          if [[ $IAM_RELEASE =~ ^v[0-9]+$ ]]; then
            "::set-output name=result::true"
          fi
  publish:
    runs-on: ubuntu-latest
    needs: release-format
    if: needs.release-format.output.should-release == 'true'
    steps:
      - name: Do something
        run: echo "${IAM_RELEASE}"
