name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determinate latest released tag
        id: current-tag
        run: |-
          # no specific tag is entered
          branch=${GITHUB_REF#refs/heads/}
          tag=$( git tag -l --merged "$branch" "*" --sort=-committerdate | head -n 1 );
          echo "::set-output name=tag::$tag";

      - name: Generate changelog
        uses: dlavrenuek/conventional-changelog-action@v1.0.1
        id: changelog
        with:
          from: ${{ steps.current-tag.outputs.tag }}
          to: ${{ steps.set-commitish.outputs.commitish }}

      - name: some tests
        run: |-
          echo ${{ steps.changelog.outputs.changelog }}
          echo ${{ toJSON(steps.changelog.outputs.changelog) }}
          echo ${{ toJSON("") }}
          echo "${{ toJSON(steps.changelog.outputs.changelog) }}"
