on:
  push:
    branches: [master, v*]

env:
  TEST_BRANCH: "v123"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |-
          echo "${{ toJson(github.event_name) }}";
          echo "${{ toJson(github.event_name == 'push') }}";
          echo "${{ github.ref }}";
          echo "${{ toJson('refs/heads/${{ env.TEST_BRANCH }}') }}";
          echo "${{ toJson(github.event_name == 'push' && github.ref == 'refs/heads/${{ env.TEST_BRANCH }}') }}";
          echo "${{ toJson(github.event) }}";

      - if: github.event_name == 'push' && github.ref == 'refs/heads/${{ env.TEST_BRANCH }}'
        run: echo "RUNS!"
