name: print release info

on:
  release:
    types: [ released ]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print target commitish
        run: echo "${{ github.event.release.target_commitish }}";

      - name: print ref
        run: echo "${{ github.ref }}";

      - name: print ref
        run: echo "${{ toJson(github.event.release) }}";

      - name: Determine Docker Image Label
        run: |-
          releaseSource="${{ github.event.release.target_commitish }}"
          if [[ $releaseSource =~ [0-9a-f]{40} ]] || [ $releaseSource == "master" ]; then
            # on master if a commit sha or the master branch was picked
            echo "ON=master" >> $GITHUB_ENV
          else
            # otherwise release is triggered from a branch
            echo "ON=$releaseSource" >> $GITHUB_ENV
          fi

      - name: print ON
        run: echo "$ON";