name: test release format v*.*.*

on:
  release:
    types: [ released ]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print target commitish
        run: echo "${{ github.event.release.target_commitish }}";

      - name: print ref
        run: echo "${{ github.ref }}";
