on:
  push:
    branches: [master, v*]
  pull_request:
    branches: ['**']

env:
  TEST_BRANCH: "v123"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test-branch
        run: echo "::set-output name=ref::refs/heads/${{ env.TEST_BRANCH }}";
      - run: |-
          echo "${{ toJson(github.event_name) }}";
          echo "${{ toJson(github.event_name == 'push') }}";
          echo "${{ github.ref }}";
          echo "${{ steps.test-branch.outputs.ref }}";
          echo "${{ toJson(github.event_name == 'push' && github.ref == steps.test-branch.outputs.ref) }}";

      - if: ${{ github.event_name == 'push' && github.ref == steps.test-branch.outputs.ref }}
        run: echo "RUNS!"

