name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print some tags
        run: |-
          branch=${GITHUB_REF#refs/heads/}
          echo "all"
          git tag -l --merged "$branch" "*" --sort=-committerdate
          echo "filtered"
          git tag -l --merged "$branch" "*" --sort=-committerdate | grep -E "^[0-9]+.[0-9]+.[0-9]+$"
