name: print release info

on:
  release:
    types: [ released ]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print target commitish
        run: echo "${{ github.event.release.target_commitish }}";

      - name: print ref
        run: echo "${{ github.ref }}";

      - name: print ref
        run: echo "${{ toJson(github.event.release) }}";

      - name: Determine Docker Image Label
        run: |-
          if [[ "${{ github.event.release.target_commitish }}" =~ [0-9a-f]{40} ]]; then
            echo "ON=${{ github.event.release.target_commitish }}" >> $GITHUB_ENV
          else
            echo "ON=master" >> $GITHUB_ENV
          fi

      - name: print ON
        run: echo "$ON";